### ISSUE TITLE
Build fails when pulling the image.

### ISSUE THREAD

**Issue by ajainrh** [openshift-roadshow/mlbparks#15]
When I run oc new-app mlbparks -p APPLICATION_NAME=mlbparks command to create mlbparks app using template, the build fails and it gives me this error
[user30:~] $ oc logs -f bc/mlbparks
Cloning "https://github.com/openshift-roadshow/mlbparks.git" ...
        Commit: 07a64a4006213736104402a025c5c8ac9b003a3a (Remove deploy task)
        Author: Natale Vinto <nvinto@redhat.com>
        Date:   Mon Jun 13 10:00:15 2022 +0200
Caching blobs under "/var/cache/blobs".
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
Warning: Pull failed, retrying in 5s ...
error: build error: After retrying 2 times, Pull image still failed due to error: Error in
itializing source docker://image-registry.openshift-image-registry.svc:5000/openshift/jbos
s-eap70-openshift@sha256:e4bfab9ef57cff6e85cc5edc184252282d8e9ff240d8f2b99ebba0e771fd1da5:
 Error reading manifest sha256:e4bfab9ef57cff6e85cc5edc184252282d8e9ff240d8f2b99ebba0e771f
d1da5 in image-registry.openshift-image-registry.svc:5000/openshift/jboss-eap70-openshift:
 unknown: unable to pull manifest from registry.redhat.io/jboss-eap-7/eap70-openshift@sha2
56:e4bfab9ef57cff6e85cc5edc184252282d8e9ff240d8f2b99ebba0e771fd1da5: unsupported: V2 schem
a 1 manifest digests are no longer supported for image pulls. Use the equivalent V2 schema
 2 manifest digest instead. For more information see https://access.redhat.com/articles/61
38332

https://access.redhat.com/articles/6138332 suggests that the v2-schema-1 is no longer supported. Please fix the issue asap as it affects my Workshops.

**Comment by 9strands** [comment]
For more details the local GUID of this failure is "rh8918" and is available on our admin host.  I can provide via internal chat to assist.

  From what I can tell, the digest seems to be at issue, but I'm not certain of how to find the new digest for this.  The related lab is OCP4_GETTING_STARTED_WKSP

**Comment by blues-man** [comment]
Hello, this has been fixed here: https://github.com/openshift-roadshow/mlbparks/commit/34ba0064793edf0079f540b9ba2feeb777ddaf2d

**Comment by blues-man** [comment]
Closing with your fix suggestion, thanks!
